user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

tag:
    resource: "@AppBundle/Resources/config/routing/tag.yml"
    prefix:   /tag/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin