services:
    user.admin.user:
        class: UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Users" }
        arguments:
            - ~
            - UserBundle\Entity\User
            - SonataAdminBundle:CRUD
        calls:
            - [ setTranslationDomain, [UserBundle]]